export default [{ "id": 1, "title": "To Kill with Intrigue (Jian hua yan yu Jiang Nan)", "writer": "SIOUX YERRELL", "published": 1994 },
{ "id": 2, "title": "Dirty Dozen: The Deadly Mission", "writer": "JAQUELIN DE ATTA", "published": 1970 },
{ "id": 3, "title": "Ghost", "writer": "MERCEDES HULLIN", "published": 1993 },
{ "id": 4, "title": "Friday the 13th Part VIII: Jason Takes Manhattan", "writer": "TRISTAM LESCOP", "published": 1996 },
{ "id": 5, "title": "Last September, The", "writer": "KARLEN SOUTHARD", "published": 1995 },
{ "id": 6, "title": "Brother (Hermano)", "writer": "BLAINE EPPSON", "published": 1997 },
{ "id": 7, "title": "American Idiots", "writer": "FLO CLOWNEY", "published": 2002 },
{ "id": 8, "title": "Hit List, The", "writer": "ILSA LATTOS", "published": 2003 },
{ "id": 9, "title": "Connections", "writer": "HOLLIS SHANAHAN", "published": 2007 },
{ "id": 10, "title": "Ladies They Talk About", "writer": "MANUEL WUDELAND", "published": 1985 },
{ "id": 11, "title": "Conflict", "writer": "MARGY DAWIDMAN", "published": 2005 },
{ "id": 12, "title": "Cousin Angelica (La prima Angélica)", "writer": "ALARIC MUZZINI", "published": 2010 },
{ "id": 13, "title": "Any Day Now", "writer": "HOLLY-ANNE SHERAR", "published": 2009 },
{ "id": 14, "title": "\"Great Performances\" Cats", "writer": "MYRANDA TOONE", "published": 2000 },
{ "id": 15, "title": "Girl Crazy", "writer": "BRADAN RICKWOOD", "published": 2011 },
{ "id": 16, "title": "Margaret", "writer": "KATHERINA VIDGEN", "published": 1999 },
{ "id": 17, "title": "Love in Another Language (Baska Dilde Ask)", "writer": "LILIAN PINCHIN", "published": 1990 },
{ "id": 18, "title": "A Story of Children and Film", "writer": "BLONDELLE VERNE", "published": 2012 },
{ "id": 19, "title": "Mister Johnson", "writer": "ROCK BREAZEALL", "published": 1989 },
{ "id": 20, "title": "Sixpack (Pussikaljaelokuva)", "writer": "DEDRA ROCHEWELL", "published": 2001 },
{ "id": 21, "title": "Roommate, The", "writer": "FRANCESCO ELLINGWORTH", "published": 2007 },
{ "id": 22, "title": "Attack, The", "writer": "LOCKWOOD WITTRINGTON", "published": 2012 },
{ "id": 23, "title": "Captain Ron", "writer": "JAYSON SHEVLAN", "published": 2008 },
{ "id": 24, "title": "Island, The (a.k.a. Naked Island) (Hadaka no shima)", "writer": "SAL PERRINS", "published": 2001 },
{ "id": 25, "title": "K.G. (Karate Girl)", "writer": "ETTORE MORMAN", "published": 1996 },
{ "id": 26, "title": "Happy New Year", "writer": "CARLOTA TWAMLEY", "published": 1997 },
{ "id": 27, "title": "Dispatch from Reuter's, A", "writer": "RICORIKI BROSH", "published": 2009 },
{ "id": 28, "title": "It's a Disaster", "writer": "GERTI WILKISSON", "published": 2003 },
{ "id": 29, "title": "Gold", "writer": "PATRICE VASSANO", "published": 2010 },
{ "id": 30, "title": "Storage 24", "writer": "ROCK UZIELLI", "published": 2005 },
{ "id": 31, "title": "Resurrection", "writer": "JERMAINE CHEZELLE", "published": 1993 },
{ "id": 32, "title": "Annapolis", "writer": "CASPAR RAFE", "published": 2012 },
{ "id": 33, "title": "1941", "writer": "SHERLOCK BROWNJOHN", "published": 1967 },
{ "id": 34, "title": "War Witch (Rebelle)", "writer": "CINDA KLIMKOVICH", "published": 2009 },
{ "id": 35, "title": "Doctor Who", "writer": "SMITTY JOSOWITZ", "published": 1992 },
{ "id": 36, "title": "Two Days", "writer": "DYANNE REDGATE", "published": 2010 },
{ "id": 37, "title": "Long Voyage Home, The", "writer": "JENNILEE BURGISS", "published": 2012 },
{ "id": 38, "title": "Alone for Christmas", "writer": "ALISSA WOLFENDEN", "published": 1985 },
{ "id": 39, "title": "Noise", "writer": "GREGG WOODING", "published": 1995 },
{ "id": 40, "title": "Children of Hiroshima (Gembaku no ko)", "writer": "KERWIN TITMUS", "published": 2007 },
{ "id": 41, "title": "Lamp in the Dark; The Untold History of the Bible, A", "writer": "GRIFFY ADDINALL", "published": 2006 },
{ "id": 42, "title": "44 Inch Chest", "writer": "MAXY RIBEIRO", "published": 2011 },
{ "id": 43, "title": "Bobcat Goldthwait: You Don't Look the Same Either", "writer": "EMMA CHESSMAN", "published": 2005 },
{ "id": 44, "title": "Wrecked", "writer": "JEMIMA SHALLCROSS", "published": 1954 },
{ "id": 45, "title": "Sudden Death", "writer": "THACHER KITTERINGHAM", "published": 2003 },
{ "id": 46, "title": "Just Around the Corner", "writer": "ODESSA BULPITT", "published": 2005 },
{ "id": 47, "title": "My Sister Eileen", "writer": "NORMAND KALKOFER", "published": 2010 },
{ "id": 48, "title": "Paradise Lost 2: Revelations", "writer": "JACLIN LUBECK", "published": 1986 },
{ "id": 49, "title": "Captains of the Clouds", "writer": "AINSLEY CHOLOMIN", "published": 2005 },
{ "id": 50, "title": "Bill & Ted's Excellent Adventure", "writer": "DORE ESTABLE", "published": 1994 },
{ "id": 51, "title": "Bill & Ted's Excellent Adventure 2", "writer": "DORE ESTABLE", "published": 1994 }]